feat: Add badges
sozercan/aikit pull request #286
Opened 2024-06-08 13:11 UTC by reneleonhardt

**What this PR does / why we need it**:

### Features
* Add some badges

[![Latest Release](https://img.shields.io/github/v/release/sozercan/aikit.svg)](https://github.com/sozercan/aikit/releases/latest) [![Docs](https://img.shields.io/badge/docs-current-brightgreen.svg)](https://sozercan.github.io/aikit/docs/) [![Test Status](https://github.com/sozercan/aikit/workflows/test/badge.svg)](https://github.com/sozercan/aikit/actions?query=workflow%3Atest) [![GoDoc](https://godoc.org/github.com/sozercan/aikit?status.svg)](https://godoc.org/github.com/sozercan/aikit) [![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-blue?logo=gitpod&style=flat-square)](https://gitpod.io/#https://github.com/sozercan/aikit) [![Go Report](https://goreportcard.com/badge/github.com/sozercan/aikit)](https://goreportcard.com/report/github.com/sozercan/aikit) [![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/sozercan/aikit/badge)](https://securityscorecards.dev/viewer/?uri=github.com/sozercan/aikit) [![License](https://img.shields.io/badge/License-MIT-blue.svg)](https://github.com/sozercan/aikit/blob/main/LICENSE) [![Go 1.21](https://img.shields.io/badge/Go-%2300ADD8.svg?&logo=go&logoColor=white)](https://go.dev/)

* Update dependencies

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
### Fixes
* Linted Dockerfile
* Typos, anchors and links in README

**Special notes for your reviewer**:
### Recommendations
* Rename all `test` jobs to `CI` to show a more self-explaining and shorter 3rd badge

2024-06-08 17:10 UTC, sozercan requested changes

2024-06-08 17:10 UTC, sozercan commented on pkg/aikit2llb/finetune/convert.go
> +	unslothCommitOrTag = "June-2024"
please keep the code changes in separate PR(s) and make sure these are tested and working. finetune has a github action called `test-finetune.yaml`, however this requires a runner with a gpu

2024-06-08 17:10 UTC, sozercan commented on .github/dependabot.yaml
> +      interval: "daily"
let's keep at weekly for all otherwise there are too many PRs generated that don't require immediate action

2024-06-08 17:10 UTC, sozercan commented on .github/dependabot.yaml
> +    directory: /charts/aikit
i don't think there's anything in the charts that needs dependabot but we can keep with weekly

2024-06-08 17:10 UTC, sozercan commented on README.md
> +[![Latest Release](https://img.shields.io/github/v/release/sozercan/aikit.svg)](https://github.com/sozercan/aikit/releases/latest)
I am not sure what value these badges add, since the information like releases, stars, licenses etc are already in the github page. I would like to keep the readme concise as possible. If there's a use case for a specific one that's needed, I am happy to include specific ones.

2024-06-08 17:32 UTC, reneleonhardt commented on pkg/aikit2llb/finetune/convert.go
> +	unslothCommitOrTag = "June-2024"
I tested locally as much as I can, but I couldn't login yet for YAML `#syntax=`.

2024-06-08 17:32 UTC, reneleonhardt commented on .github/dependabot.yaml
> +      interval: "daily"
`weekly` set

2024-06-08 17:32 UTC, reneleonhardt commented on README.md
> +[![Latest Release](https://img.shields.io/github/v/release/sozercan/aikit.svg)](https://github.com/sozercan/aikit/releases/latest)
Reverted badges and changed description and title

2024-06-12 09:00 UTC, sozercan commented
Thanks! Fixed a few minor merge conflicts, should be good after CI pass.

2024-06-12 10:12 UTC, sozercan approved these changes
LGTM

2024-06-12 10:18 UTC, merged